<?php
require_once("functions/page-speed.php");
require_once("functions/theme-features.php");
require_once("functions/menus.php");
require_once("functions/styles-scripts.php");
require_once("functions/image-sizes.php");
require_once("functions/filters.php");
require_once("functions/shortcodes.php");
require_once("functions/custom-functions.php");
require_once("functions/advanced-custom-fields.php");
