<?php
require_once(get_theme_file_path("/functions/vendor.php"));
require_once(get_theme_file_path("/functions/custom-functions.php"));
require_once(get_theme_file_path("/functions/filters.php"));
require_once(get_theme_file_path("/functions/image-sizes.php"));
require_once(get_theme_file_path("/functions/menus.php"));
require_once(get_theme_file_path("/functions/meta.php"));
require_once(get_theme_file_path("/functions/page-speed.php"));
require_once(get_theme_file_path("/functions/post-types.php"));
require_once(get_theme_file_path("/functions/progressive-web-app.php"));
require_once(get_theme_file_path("/functions/rewrite-rules.php"));
require_once(get_theme_file_path("/functions/shortcodes.php"));
require_once(get_theme_file_path("/functions/styles-scripts.php"));
require_once(get_theme_file_path("/functions/theme-features.php"));
require_once(get_theme_file_path("/functions/advanced-custom-fields.php"));
require_once(get_theme_file_path("/functions/tribe-events.php"));
